# Generated by Django 4.1.3 on 2022-12-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='image',
            field=models.ImageField(default='sinperfil.png', upload_to=''),
        ),
    ]
