# Generated by Django 4.1.3 on 2022-12-09 02:07

from django.db import migrations, models
import mensajes.models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0007_alter_usuarios_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='image',
            field=models.ImageField(blank=True, default='sinperfil.png', upload_to=mensajes.models.create_path),
        ),
    ]
