# Generated by Django 4.1.3 on 2022-12-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0009_verificacioncuentas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacioncuentas',
            name='fecha_autenticacion',
            field=models.DateTimeField(blank=True, verbose_name='fecha autenticacion'),
        ),
    ]
