# Generated by Django 4.1.3 on 2022-12-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0011_alter_verificacioncuentas_fecha_autenticacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='sexo',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
